### ISSUE TITLE
First item aligned wrong

### ISSUE THREAD

**Issue by mkleehammer** [leejarvis/assign-align#1]
I had four lines, but something like this:

a = 1
ab = 2

Highlighted both lines using cmd-l.  Results were:
    a = 1
ab = 2

**Comment by ghost** [comment]
:thumbsup: I am also seeing wonky behavior on the first line

before

``` ruby
@thing = foo
@another_thing = bar
@something_else = baz
```

after

``` ruby
                @thing          = foo
@another_thing  = bar
@something_else = baz
```

expected

``` ruby
@thing          = foo
@another_thing  = bar
@something_else = baz
```

**Comment by leejarvis** [comment]
This package is no longer maintained. I have updated the README and suggest using https://atom.io/packages/atom-alignment instead. Thanks
